<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CampagnesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('campagnes')->delete();
        
        \DB::table('campagnes')->insert(array (
            0 => 
            array (
                'id_campagne' => 0,
                'nom' => 'Bonjour Laura',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => 'Terminée',
                'contenu_post_mere' => '3 juin, 10:57 · ',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id_campagne' => 1,
                'nom' => 'Eloise',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => NULL,
                'contenu_post_mere' => 'Eloise',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => '2023-03-08 16:14:21',
            ),
            2 => 
            array (
                'id_campagne' => 2,
                'nom' => 'Bonjour Juin',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'Bonjour Juin',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id_campagne' => 3,
                'nom' => 'Jaqueline',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'La Fête des Mamans',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id_campagne' => 4,
                'nom' => 'Bonjour Juillet',
                'score' => '0.00',
                'date_debut' => '2021-07-02',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'Bonjour Juillet',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id_campagne' => 5,
                'nom' => 'Montagnes',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'liberté, de belles expériences',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id_campagne' => 6,
                'nom' => 'Experience LLC',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'une expérience magique',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id_campagne' => 7,
                'nom' => 'Chanson d\'amour',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'chanson d\'amour',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bian',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id_campagne' => 8,
                'nom' => 'Retrouvailles',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => 'contexte',
                'etat' => '',
                'contenu_post_mere' => 'super heureux',
                'objectifs' => 'objectifs',
                'recommandation' => 'recommandation',
                'bilan' => 'bilan',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id_campagne' => 10,
                'nom' => 'Bonjour Mars',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => NULL,
                'contenu_post_mere' => 'lève sur mars',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => '2023-03-17 17:50:27',
            ),
            10 => 
            array (
                'id_campagne' => 11,
                'nom' => 'Chanter son Histoir',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'vivre une expérience, garder des souvenirs',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id_campagne' => 12,
                'nom' => 'Bonne journée mercredi ',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'belle journée',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id_campagne' => 13,
                'nom' => 'Bonne année',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'année 2021',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id_campagne' => 14,
                'nom' => 'testtt',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => NULL,
                'contenu_post_mere' => NULL,
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => '2023-03-10 18:21:23',
            ),
            14 => 
            array (
                'id_campagne' => 15,
                'nom' => 'Bonjour Août',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'Joyeux mois d\'août ☀️☀️☀️ et beaucoup de belles expériences',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id_campagne' => 16,
                'nom' => 'Rentrée',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => '',
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id_campagne' => 17,
                'nom' => 'Jour 2  septembre',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id_campagne' => 18,
                'nom' => 'Noemie expérience',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'Aujourd\'hui nous vous faisons découvrir Noémie, elle interprète No Time To Die, une James Bond Girl qui nous donne des frissons ...????
L\'expérience LalaChante, un moment que l\'on aime partager ... ???? ✨
➡️www.lalachante.fr
#billieeilish',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id_campagne' => 19,
                'nom' => 'Quitterie',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'Pour vous souhaiter un bon weekend nous vous partageons l\'Expérience de Quitterie',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id_campagne' => 20,
                'nom' => 'Un jour d\'octobre',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'Un post qui inspire, bonne journée à tous ... ????✨',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id_campagne' => 21,
                'nom' => 'Présentation Aurore 211014',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id_campagne' => 22,
                'nom' => 'Expérience Clara',
                'score' => NULL,
                'date_debut' => NULL,
                'date_fin' => NULL,
                'contexte' => NULL,
                'etat' => '',
                'contenu_post_mere' => 'Aujourd\'hui nous vous partageons l\'expérience de Clara, qui interprète This Is Me 🔥.',
                'objectifs' => NULL,
                'recommandation' => NULL,
                'bilan' => NULL,
                'date_programmation' => NULL,
                'nb_likes' => NULL,
                'nb_comments' => NULL,
                'nb_shares' => NULL,
                'portee' => NULL,
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id_campagne' => 23,
                'nom' => 'Un jour de novembre',
                'score' => '0.00',
                'date_debut' => '2021-11-18',
                'date_fin' => '0000-00-00',
                'contexte' => '',
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => '',
                'recommandation' => '',
                'bilan' => '',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id_campagne' => 24,
                'nom' => 'Présentation Chloé Novembre ',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => '',
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => '',
                'recommandation' => '',
                'bilan' => '',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '6673',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id_campagne' => 25,
                'nom' => 'Présentation Aurore Novembre',
                'score' => '0.00',
                'date_debut' => '0000-00-00',
                'date_fin' => '0000-00-00',
                'contexte' => '',
                'etat' => '',
                'contenu_post_mere' => '',
                'objectifs' => '',
                'recommandation' => '',
                'bilan' => '',
                'date_programmation' => '0000-00-00',
                'nb_likes' => '0',
                'nb_comments' => '0',
                'nb_shares' => '0',
                'portee' => '0',
                'id_segmentation' => '6673',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id_campagne' => 26,
            'nom' => 'Vivre L\'essentiel  ( Le temps d\'une chanson) ',
                'score' => '0.00',
                'date_debut' => '2021-11-18',
                'date_fin' => '2021-11-18',
            'contexte' => '-> Vérifier l\'historique post ds les groupes avant de poster ! ) . ',
            'etat' => '',
        'contenu_post_mere' => 'Vivre L\'essentiel  ( Le temps d\'une chanson)  ... ',
        'objectifs' => 'Com : grand public, valeur de LCC. Cible : tout segments ->(Segment 2 segmentation A uniquement) ',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '2021-11-18',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        26 => 
        array (
            'id_campagne' => 27,
            'nom' => 'Black Fryday',
            'score' => '0.00',
            'date_debut' => '2021-11-26',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '6',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        27 => 
        array (
            'id_campagne' => 30,
        'nom' => 'Jour 2 Décembre 2021  ( seg1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        28 => 
        array (
            'id_campagne' => 31,
        'nom' => 'Jour 2 Décembre 2021 ( seg2)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        29 => 
        array (
            'id_campagne' => 32,
        'nom' => 'Jour 2 Décembre 2021 ( seg3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        30 => 
        array (
            'id_campagne' => 33,
        'nom' => 'Jour 2 Décembre 2021 ( seg4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        31 => 
        array (
            'id_campagne' => 34,
        'nom' => 'Jour 2 Décembre 2021 ( seg5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        32 => 
        array (
            'id_campagne' => 35,
        'nom' => 'Calendrier de l\'Avent (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        33 => 
        array (
            'id_campagne' => 36,
        'nom' => 'Calendrier de l\'Avent (S2)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        34 => 
        array (
            'id_campagne' => 37,
        'nom' => 'Calendrier de l\'Avent (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        35 => 
        array (
            'id_campagne' => 38,
        'nom' => 'Calendrier de l\'Avent (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        36 => 
        array (
            'id_campagne' => 39,
        'nom' => 'Calendrier de l\'Avent (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        37 => 
        array (
            'id_campagne' => 40,
        'nom' => 'Décompte Noël (S PROMO)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        38 => 
        array (
            'id_campagne' => 41,
        'nom' => 'Décompte Noël (S MOYEN)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        39 => 
        array (
            'id_campagne' => 42,
        'nom' => 'Décompte Noël (GRPES AVESTA)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        40 => 
        array (
            'id_campagne' => 43,
        'nom' => 'EXPÉRIENCE KIM & KARIMA (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        41 => 
        array (
            'id_campagne' => 44,
        'nom' => 'EXPÉRIENCE KIM & KARIMA (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        42 => 
        array (
            'id_campagne' => 45,
        'nom' => 'EXPÉRIENCE KIM & KARIMA (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        43 => 
        array (
            'id_campagne' => 46,
        'nom' => 'EXPÉRIENCE KIM & KARIMA (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        44 => 
        array (
            'id_campagne' => 47,
        'nom' => 'EXPÉRIENCE KIM & KARIMA (GRPES AVESTA)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        45 => 
        array (
            'id_campagne' => 48,
        'nom' => 'EXPÉRIENCE LILY ROSE (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        46 => 
        array (
            'id_campagne' => 49,
        'nom' => 'EXPÉRIENCE LILY ROSE (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        47 => 
        array (
            'id_campagne' => 50,
        'nom' => 'EXPÉRIENCE LILY ROSE (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        48 => 
        array (
            'id_campagne' => 51,
        'nom' => 'EXPÉRIENCE LILY ROSE (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        49 => 
        array (
            'id_campagne' => 52,
        'nom' => 'EXPÉRIENCE LILY ROSE (S GRPES AVESTA)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '7',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        50 => 
        array (
            'id_campagne' => 53,
        'nom' => 'EXPÉRIENCE CLARA (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        51 => 
        array (
            'id_campagne' => 54,
        'nom' => 'EXPÉRIENCE CLARA (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        52 => 
        array (
            'id_campagne' => 55,
        'nom' => 'EXPÉRIENCE CLARA (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        53 => 
        array (
            'id_campagne' => 56,
        'nom' => 'EXPÉRIENCE CLARA (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        54 => 
        array (
            'id_campagne' => 57,
        'nom' => 'Carrousel (PROMO)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        55 => 
        array (
            'id_campagne' => 58,
        'nom' => 'EXPÉRIENCE HUGO (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        56 => 
        array (
            'id_campagne' => 59,
        'nom' => 'EXPÉRIENCE HUGO (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        57 => 
        array (
            'id_campagne' => 60,
        'nom' => 'EXPÉRIENCE HUGO (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        58 => 
        array (
            'id_campagne' => 61,
        'nom' => 'EXPÉRIENCE HUGO (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        59 => 
        array (
            'id_campagne' => 62,
            'nom' => 'Achat/ Vente',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        60 => 
        array (
            'id_campagne' => 63,
        'nom' => 'EXPÉRIENCE B&C&S (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        61 => 
        array (
            'id_campagne' => 64,
        'nom' => 'EXPÉRIENCE B&C&S (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        62 => 
        array (
            'id_campagne' => 66,
        'nom' => 'EXPÉRIENCE B&C&S (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        63 => 
        array (
            'id_campagne' => 67,
        'nom' => 'BONNE ANNÉE (S1)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        64 => 
        array (
            'id_campagne' => 68,
        'nom' => 'BONNE ANNÉE (S2)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        65 => 
        array (
            'id_campagne' => 69,
        'nom' => 'BONNE ANNÉE (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        66 => 
        array (
            'id_campagne' => 70,
        'nom' => 'BONNE ANNÉE (S4)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        67 => 
        array (
            'id_campagne' => 71,
        'nom' => 'BONNE ANNÉE (S5)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        68 => 
        array (
            'id_campagne' => 72,
        'nom' => 'Paysage Montagne (S1)',
            'score' => '0.00',
            'date_debut' => '2022-01-22',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        69 => 
        array (
            'id_campagne' => 73,
        'nom' => 'Paysage Montagne (S2)',
            'score' => '0.00',
            'date_debut' => '2022-01-22',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        70 => 
        array (
            'id_campagne' => 74,
        'nom' => 'Paysage Montagne (S3)',
            'score' => '0.00',
            'date_debut' => '2022-01-22',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        71 => 
        array (
            'id_campagne' => 75,
        'nom' => 'Paysage Montagne (S4)',
            'score' => '0.00',
            'date_debut' => '2022-01-22',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        72 => 
        array (
            'id_campagne' => 76,
        'nom' => 'Paysage Montagne (S5)',
            'score' => '0.00',
            'date_debut' => '2022-01-22',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        73 => 
        array (
            'id_campagne' => 77,
        'nom' => 'Un instant pour LUI (S1)',
            'score' => '0.00',
            'date_debut' => '2022-01-26',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        74 => 
        array (
            'id_campagne' => 78,
        'nom' => 'Un instant pour LUI (S3)',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '2022-01-26',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        75 => 
        array (
            'id_campagne' => 79,
        'nom' => 'Un instant pour LUI (S4)',
            'score' => '0.00',
            'date_debut' => '2022-01-26',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        76 => 
        array (
            'id_campagne' => 80,
        'nom' => 'Un instant pour LUI (S5)',
            'score' => '0.00',
            'date_debut' => '2022-01-26',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        77 => 
        array (
            'id_campagne' => 82,
            'nom' => 'Clement2',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        78 => 
        array (
            'id_campagne' => 666,
            'nom' => 'Jour 2  Décembre 2021',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        79 => 
        array (
            'id_campagne' => 667,
        'nom' => '(INvisible)Jour 2  Décembre 2021',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        80 => 
        array (
            'id_campagne' => 671,
        'nom' => 'Dernier jours de Mars 2022 ( Segment 1 )',
            'score' => '0.00',
            'date_debut' => '2022-03-31',
            'date_fin' => '0000-00-00',
        'contexte' => '( Segment 1 ) 50 // Laura / Mehdi',
            'etat' => '',
            'contenu_post_mere' => 'Bonjour  xxxx c\'est Laura ???? Petit post pour vous souhaiter une belle Fin de journée et de semaine à tous ????✨',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '2022-03-31',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        81 => 
        array (
            'id_campagne' => 672,
        'nom' => 'Dernier jours de Mars 2022 ( Segment 2 )  ',
            'score' => '0.00',
            'date_debut' => '2022-03-31',
            'date_fin' => '0000-00-00',
        'contexte' => ' ( Segment 2 )  ',
            'etat' => '',
            'contenu_post_mere' => 'Bonjour  , c\'est Cloé ???? Petit post pour vous souhaiter une belle  fin de journée ✨  Jolie fin de semaine à tous ????',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '2022-03-31',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        82 => 
        array (
            'id_campagne' => 673,
        'nom' => 'Dernier jours de Mars 2022 ( Segment 3 )',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
        'contexte' => '  ( Segment 3 )',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        83 => 
        array (
            'id_campagne' => 674,
        'nom' => 'Dernier jours de Mars 2022 ( Segment 4 )',
            'score' => '0.00',
            'date_debut' => '2022-03-31',
            'date_fin' => '0000-00-00',
        'contexte' => ' ( Segment 4 )',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        84 => 
        array (
            'id_campagne' => 675,
        'nom' => 'Dernier jours de Mars 2022 ( Segment 5 )',
            'score' => '0.00',
            'date_debut' => '2022-03-31',
            'date_fin' => '0000-00-00',
        'contexte' => '( Segment 5 )',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        85 => 
        array (
            'id_campagne' => 676,
        'nom' => 'journée mondiale de l\'art (segment 1)',
            'score' => '0.00',
            'date_debut' => '2022-04-15',
            'date_fin' => '0000-00-00',
            'contexte' => 'Segment 1',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        86 => 
        array (
            'id_campagne' => 679,
        'nom' => 'journée mondiale de l\'art (segment 3)',
            'score' => '0.00',
            'date_debut' => '2022-04-15',
            'date_fin' => '0000-00-00',
            'contexte' => 'Segment 3',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        87 => 
        array (
            'id_campagne' => 680,
        'nom' => 'journée mondiale de l\'art (segment 4)',
            'score' => '0.00',
            'date_debut' => '2022-04-15',
            'date_fin' => '0000-00-00',
            'contexte' => 'Segment 4',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        88 => 
        array (
            'id_campagne' => 681,
        'nom' => 'journée mondiale de l\'art (segment 5)',
            'score' => '0.00',
            'date_debut' => '2022-04-15',
            'date_fin' => '0000-00-00',
            'contexte' => 'Segment 5',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        89 => 
        array (
            'id_campagne' => 683,
            'nom' => 'journée mondiale de l\'art segment 2',
            'score' => '0.00',
            'date_debut' => '2022-04-15',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        90 => 
        array (
            'id_campagne' => 684,
            'nom' => 'Expérience Emma S1',
            'score' => '0.00',
            'date_debut' => '2022-04-22',
            'date_fin' => '0000-00-00',
            'contexte' => 'seg1 / 30 en attente',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        91 => 
        array (
            'id_campagne' => 685,
            'nom' => 'Experience EMMA S3',
            'score' => '0.00',
            'date_debut' => '2022-04-22',
            'date_fin' => '0000-00-00',
            'contexte' => 'seg3 / 14 en attente',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        92 => 
        array (
            'id_campagne' => 686,
            'nom' => 'Expérience Emma  S4',
            'score' => '0.00',
            'date_debut' => '2022-04-22',
            'date_fin' => '0000-00-00',
            'contexte' => 'seg4 / 17 en attente',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        93 => 
        array (
            'id_campagne' => 687,
            'nom' => 'experience EMMA S5',
            'score' => '28.00',
            'date_debut' => '2022-04-22',
            'date_fin' => '0000-00-00',
            'contexte' => 'Seg5 / 28 en attente',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        94 => 
        array (
            'id_campagne' => 688,
            'nom' => 'Bonjour mai segment 1 Laura',
            'score' => '0.00',
            'date_debut' => '2022-05-02',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        95 => 
        array (
            'id_campagne' => 689,
            'nom' => 'Bonjour mai segment 2',
            'score' => '0.00',
            'date_debut' => '2022-05-02',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        96 => 
        array (
            'id_campagne' => 690,
            'nom' => 'Bonjour Mai segment 3',
            'score' => '0.00',
            'date_debut' => '2022-05-02',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        97 => 
        array (
            'id_campagne' => 691,
            'nom' => 'Bonjour mai segment 4',
            'score' => '0.00',
            'date_debut' => '2022-05-02',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        98 => 
        array (
            'id_campagne' => 692,
            'nom' => 'Bonjour mai segment 5',
            'score' => '0.00',
            'date_debut' => '2022-05-02',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        99 => 
        array (
            'id_campagne' => 694,
            'nom' => 'Campagne Léa vendredi 13 S1',
            'score' => '0.00',
            'date_debut' => '2022-05-12',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        100 => 
        array (
            'id_campagne' => 695,
            'nom' => 'Campagne Léa 13 mai S2',
            'score' => '0.00',
            'date_debut' => '2022-05-12',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '2',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        101 => 
        array (
            'id_campagne' => 696,
            'nom' => 'Campagne Léa 13 mai S3',
            'score' => '0.00',
            'date_debut' => '2022-05-12',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        102 => 
        array (
            'id_campagne' => 697,
            'nom' => 'Campagne Léa 13 mai S4',
            'score' => '0.00',
            'date_debut' => '2022-05-12',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        103 => 
        array (
            'id_campagne' => 698,
            'nom' => 'Campagne Léa 13 mai S5',
            'score' => '0.00',
            'date_debut' => '2022-05-12',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        104 => 
        array (
            'id_campagne' => 699,
        'nom' => 'Campagne Fête des Mères ( Segement 6 / Promo Possible ) ',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => 'Dans  un peu plus d\'une semaine c\'est la fête de maman ^^ vous avez une idée',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '6',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        105 => 
        array (
            'id_campagne' => 700,
        'nom' => 'Campagne Fête des Mères ( Segement 7 / Promo Possible si événement)',
            'score' => '0.00',
            'date_debut' => '2022-05-21',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '7',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        106 => 
        array (
            'id_campagne' => 703,
            'nom' => 'teasrarazr',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        107 => 
        array (
            'id_campagne' => 706,
            'nom' => 'reda 13',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        108 => 
        array (
            'id_campagne' => 707,
            'nom' => 'Reda 14',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        109 => 
        array (
            'id_campagne' => 709,
        'nom' => 'campagne fête des mères (seg1)',
            'score' => '0.00',
            'date_debut' => '2022-05-27',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        110 => 
        array (
            'id_campagne' => 711,
        'nom' => 'campagne fête des mères (seg3)',
            'score' => '0.00',
            'date_debut' => '2022-05-27',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '3',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        111 => 
        array (
            'id_campagne' => 712,
        'nom' => 'campagne fête des mères (seg4)',
            'score' => '0.00',
            'date_debut' => '2022-05-27',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '4',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        112 => 
        array (
            'id_campagne' => 713,
        'nom' => 'campagne fête des mères (seg5)',
            'score' => '0.00',
            'date_debut' => '2022-05-27',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '5',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        113 => 
        array (
            'id_campagne' => 715,
            'nom' => 'MamaN TOulouse',
            'score' => '0.00',
            'date_debut' => '0000-00-00',
            'date_fin' => '0000-00-00',
            'contexte' => '',
            'etat' => '',
            'contenu_post_mere' => '',
            'objectifs' => '',
            'recommandation' => '',
            'bilan' => '',
            'date_programmation' => '0000-00-00',
            'nb_likes' => '0',
            'nb_comments' => '0',
            'nb_shares' => '0',
            'portee' => '0',
            'id_segmentation' => '1',
            'created_at' => NULL,
            'updated_at' => NULL,
        ),
        114 => 
        array (
            'id_campagne' => 727,
            'nom' => '8888888888',
            'score' => NULL,
            'date_debut' => NULL,
            'date_fin' => NULL,
            'contexte' => NULL,
            'etat' => NULL,
            'contenu_post_mere' => NULL,
            'objectifs' => NULL,
            'recommandation' => NULL,
            'bilan' => NULL,
            'date_programmation' => NULL,
            'nb_likes' => NULL,
            'nb_comments' => NULL,
            'nb_shares' => NULL,
            'portee' => NULL,
            'id_segmentation' => '6',
            'created_at' => '2022-09-15 10:14:56',
            'updated_at' => '2022-09-15 10:14:56',
        ),
    ));
        
        
    }
}