<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PackExperienceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::connection('mysql2')->table('pack_experience')->delete();
        
        \DB::connection('mysql2')->table('pack_experience')->insert(array (
            0 => 
            array (
                'id_pack_experience' => 2,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 2,
                'num_facture' => 53,
                'id_experience' => 42,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            1 => 
            array (
                'id_pack_experience' => 3,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 83,
                'id_experience' => 71,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            2 => 
            array (
                'id_pack_experience' => 4,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 84,
                'id_experience' => 72,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            3 => 
            array (
                'id_pack_experience' => 16,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 96,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            4 => 
            array (
                'id_pack_experience' => 17,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 97,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            5 => 
            array (
                'id_pack_experience' => 18,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 87,
                'id_experience' => 75,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            6 => 
            array (
                'id_pack_experience' => 19,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 98,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            7 => 
            array (
                'id_pack_experience' => 29,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 117,
                'id_experience' => 76,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            8 => 
            array (
                'id_pack_experience' => 38,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 7,
                'num_facture' => 119,
                'id_experience' => 78,
                'id_liste_prix' => 22,
                'id_historique_remise' => NULL,
            ),
            9 => 
            array (
                'id_pack_experience' => 40,
                'nb_titres' => 2,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 133,
                'id_experience' => 82,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            10 => 
            array (
                'id_pack_experience' => 41,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 9,
                'num_facture' => 134,
                'id_experience' => 83,
                'id_liste_prix' => 13,
                'id_historique_remise' => NULL,
            ),
            11 => 
            array (
                'id_pack_experience' => 43,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 9,
                'num_facture' => 136,
                'id_experience' => 85,
                'id_liste_prix' => 13,
                'id_historique_remise' => NULL,
            ),
            12 => 
            array (
                'id_pack_experience' => 45,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 138,
                'id_experience' => 87,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            13 => 
            array (
                'id_pack_experience' => 46,
                'nb_titres' => 1,
                'nb_participants' => 3,
                'id_pack' => 3,
                'num_facture' => 139,
                'id_experience' => 91,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            14 => 
            array (
                'id_pack_experience' => 47,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 6,
                'num_facture' => 140,
                'id_experience' => NULL,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            15 => 
            array (
                'id_pack_experience' => 48,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 7,
                'num_facture' => 141,
                'id_experience' => 89,
                'id_liste_prix' => 22,
                'id_historique_remise' => NULL,
            ),
            16 => 
            array (
                'id_pack_experience' => 49,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 2,
                'num_facture' => 142,
                'id_experience' => 88,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            17 => 
            array (
                'id_pack_experience' => 50,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 143,
                'id_experience' => 90,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            18 => 
            array (
                'id_pack_experience' => 51,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 7,
                'num_facture' => 144,
                'id_experience' => 92,
                'id_liste_prix' => 22,
                'id_historique_remise' => NULL,
            ),
            19 => 
            array (
                'id_pack_experience' => 53,
                'nb_titres' => 2,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 146,
                'id_experience' => 93,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            20 => 
            array (
                'id_pack_experience' => 54,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 6,
                'num_facture' => 147,
                'id_experience' => 94,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            21 => 
            array (
                'id_pack_experience' => 56,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 149,
                'id_experience' => 95,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            22 => 
            array (
                'id_pack_experience' => 58,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 154,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            23 => 
            array (
                'id_pack_experience' => 100,
                'nb_titres' => 1,
                'nb_participants' => 4,
                'id_pack' => 11,
                'num_facture' => 202,
                'id_experience' => 200,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            24 => 
            array (
                'id_pack_experience' => 101,
                'nb_titres' => 1,
                'nb_participants' => 3,
                'id_pack' => 11,
                'num_facture' => 203,
                'id_experience' => 201,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            25 => 
            array (
                'id_pack_experience' => 102,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 204,
                'id_experience' => 202,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            26 => 
            array (
                'id_pack_experience' => 103,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 205,
                'id_experience' => 203,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            27 => 
            array (
                'id_pack_experience' => 104,
                'nb_titres' => 1,
                'nb_participants' => 3,
                'id_pack' => 11,
                'num_facture' => 206,
                'id_experience' => 204,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            28 => 
            array (
                'id_pack_experience' => 105,
                'nb_titres' => 1,
                'nb_participants' => 9,
                'id_pack' => 11,
                'num_facture' => 207,
                'id_experience' => 205,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            29 => 
            array (
                'id_pack_experience' => 106,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 208,
                'id_experience' => 206,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            30 => 
            array (
                'id_pack_experience' => 107,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 11,
                'num_facture' => 209,
                'id_experience' => 207,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            31 => 
            array (
                'id_pack_experience' => 108,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 210,
                'id_experience' => 208,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            32 => 
            array (
                'id_pack_experience' => 109,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 11,
                'num_facture' => 211,
                'id_experience' => 209,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            33 => 
            array (
                'id_pack_experience' => 110,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 212,
                'id_experience' => 210,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            34 => 
            array (
                'id_pack_experience' => 111,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 213,
                'id_experience' => 211,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            35 => 
            array (
                'id_pack_experience' => 112,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 214,
                'id_experience' => 212,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            36 => 
            array (
                'id_pack_experience' => 113,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 215,
                'id_experience' => 213,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            37 => 
            array (
                'id_pack_experience' => 114,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 11,
                'num_facture' => 216,
                'id_experience' => 214,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            38 => 
            array (
                'id_pack_experience' => 115,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 217,
                'id_experience' => 215,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            39 => 
            array (
                'id_pack_experience' => 116,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 218,
                'id_experience' => 216,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            40 => 
            array (
                'id_pack_experience' => 117,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 219,
                'id_experience' => 217,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            41 => 
            array (
                'id_pack_experience' => 118,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 220,
                'id_experience' => 218,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            42 => 
            array (
                'id_pack_experience' => 119,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 221,
                'id_experience' => 219,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            43 => 
            array (
                'id_pack_experience' => 120,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 222,
                'id_experience' => 220,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            44 => 
            array (
                'id_pack_experience' => 121,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 223,
                'id_experience' => 221,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            45 => 
            array (
                'id_pack_experience' => 122,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 11,
                'num_facture' => 224,
                'id_experience' => 222,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            46 => 
            array (
                'id_pack_experience' => 123,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 225,
                'id_experience' => 223,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            47 => 
            array (
                'id_pack_experience' => 124,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 226,
                'id_experience' => 224,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            48 => 
            array (
                'id_pack_experience' => 125,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 227,
                'id_experience' => 225,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            49 => 
            array (
                'id_pack_experience' => 126,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 228,
                'id_experience' => 226,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            50 => 
            array (
                'id_pack_experience' => 127,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 11,
                'num_facture' => 228,
                'id_experience' => 227,
                'id_liste_prix' => 4,
                'id_historique_remise' => NULL,
            ),
            51 => 
            array (
                'id_pack_experience' => 128,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 229,
                'id_experience' => 228,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            52 => 
            array (
                'id_pack_experience' => 129,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 230,
                'id_experience' => 229,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            53 => 
            array (
                'id_pack_experience' => 130,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 231,
                'id_experience' => 230,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            54 => 
            array (
                'id_pack_experience' => 131,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 232,
                'id_experience' => 231,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            55 => 
            array (
                'id_pack_experience' => 132,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 233,
                'id_experience' => 232,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            56 => 
            array (
                'id_pack_experience' => 133,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 234,
                'id_experience' => 233,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            57 => 
            array (
                'id_pack_experience' => 134,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 12,
                'num_facture' => 235,
                'id_experience' => 234,
                'id_liste_prix' => 1,
                'id_historique_remise' => NULL,
            ),
            58 => 
            array (
                'id_pack_experience' => 135,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 236,
                'id_experience' => 235,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            59 => 
            array (
                'id_pack_experience' => 136,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 237,
                'id_experience' => 236,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            60 => 
            array (
                'id_pack_experience' => 137,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 238,
                'id_experience' => 237,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            61 => 
            array (
                'id_pack_experience' => 138,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 239,
                'id_experience' => 238,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            62 => 
            array (
                'id_pack_experience' => 139,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 240,
                'id_experience' => 239,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            63 => 
            array (
                'id_pack_experience' => 140,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 241,
                'id_experience' => 240,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            64 => 
            array (
                'id_pack_experience' => 141,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 242,
                'id_experience' => 241,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            65 => 
            array (
                'id_pack_experience' => 142,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 243,
                'id_experience' => 242,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            66 => 
            array (
                'id_pack_experience' => 143,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 244,
                'id_experience' => 243,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            67 => 
            array (
                'id_pack_experience' => 144,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 245,
                'id_experience' => 244,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            68 => 
            array (
                'id_pack_experience' => 145,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 246,
                'id_experience' => 245,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            69 => 
            array (
                'id_pack_experience' => 146,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 247,
                'id_experience' => 246,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            70 => 
            array (
                'id_pack_experience' => 147,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 248,
                'id_experience' => 247,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            71 => 
            array (
                'id_pack_experience' => 148,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 12,
                'num_facture' => 249,
                'id_experience' => 248,
                'id_liste_prix' => 1,
                'id_historique_remise' => NULL,
            ),
            72 => 
            array (
                'id_pack_experience' => 149,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 6,
                'num_facture' => 250,
                'id_experience' => 249,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            73 => 
            array (
                'id_pack_experience' => 150,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 251,
                'id_experience' => 250,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            74 => 
            array (
                'id_pack_experience' => 151,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 252,
                'id_experience' => 251,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            75 => 
            array (
                'id_pack_experience' => 152,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 253,
                'id_experience' => 252,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            76 => 
            array (
                'id_pack_experience' => 153,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 254,
                'id_experience' => 253,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            77 => 
            array (
                'id_pack_experience' => 154,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 255,
                'id_experience' => 254,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            78 => 
            array (
                'id_pack_experience' => 155,
                'nb_titres' => 1,
                'nb_participants' => 4,
                'id_pack' => 6,
                'num_facture' => 256,
                'id_experience' => 255,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            79 => 
            array (
                'id_pack_experience' => 156,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 257,
                'id_experience' => 256,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            80 => 
            array (
                'id_pack_experience' => 157,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 258,
                'id_experience' => 257,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            81 => 
            array (
                'id_pack_experience' => 158,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 259,
                'id_experience' => 258,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            82 => 
            array (
                'id_pack_experience' => 159,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 260,
                'id_experience' => 259,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            83 => 
            array (
                'id_pack_experience' => 160,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 261,
                'id_experience' => 260,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            84 => 
            array (
                'id_pack_experience' => 161,
                'nb_titres' => 2,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 262,
                'id_experience' => 261,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            85 => 
            array (
                'id_pack_experience' => 162,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 263,
                'id_experience' => 262,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            86 => 
            array (
                'id_pack_experience' => 163,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 264,
                'id_experience' => 263,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            87 => 
            array (
                'id_pack_experience' => 164,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 265,
                'id_experience' => 264,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            88 => 
            array (
                'id_pack_experience' => 165,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 266,
                'id_experience' => 265,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            89 => 
            array (
                'id_pack_experience' => 166,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 267,
                'id_experience' => 266,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            90 => 
            array (
                'id_pack_experience' => 167,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 268,
                'id_experience' => 267,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            91 => 
            array (
                'id_pack_experience' => 168,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 269,
                'id_experience' => 268,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            92 => 
            array (
                'id_pack_experience' => 169,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 270,
                'id_experience' => 269,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            93 => 
            array (
                'id_pack_experience' => 170,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 271,
                'id_experience' => 270,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            94 => 
            array (
                'id_pack_experience' => 171,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 6,
                'num_facture' => 272,
                'id_experience' => 271,
                'id_liste_prix' => 48,
                'id_historique_remise' => NULL,
            ),
            95 => 
            array (
                'id_pack_experience' => 172,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 273,
                'id_experience' => 272,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            96 => 
            array (
                'id_pack_experience' => 173,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 12,
                'num_facture' => 274,
                'id_experience' => 273,
                'id_liste_prix' => 1,
                'id_historique_remise' => NULL,
            ),
            97 => 
            array (
                'id_pack_experience' => 174,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 275,
                'id_experience' => 274,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            98 => 
            array (
                'id_pack_experience' => 175,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 277,
                'id_experience' => 275,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            99 => 
            array (
                'id_pack_experience' => 176,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 278,
                'id_experience' => 276,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            100 => 
            array (
                'id_pack_experience' => 177,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 279,
                'id_experience' => 277,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            101 => 
            array (
                'id_pack_experience' => 178,
                'nb_titres' => 1,
                'nb_participants' => 3,
                'id_pack' => 6,
                'num_facture' => 280,
                'id_experience' => 278,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            102 => 
            array (
                'id_pack_experience' => 179,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 14,
                'num_facture' => 281,
                'id_experience' => 279,
                'id_liste_prix' => 47,
                'id_historique_remise' => NULL,
            ),
            103 => 
            array (
                'id_pack_experience' => 180,
                'nb_titres' => 1,
                'nb_participants' => 5,
                'id_pack' => 13,
                'num_facture' => 283,
                'id_experience' => 280,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            104 => 
            array (
                'id_pack_experience' => 181,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 284,
                'id_experience' => 281,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            105 => 
            array (
                'id_pack_experience' => 182,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 286,
                'id_experience' => 282,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            106 => 
            array (
                'id_pack_experience' => 183,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 287,
                'id_experience' => 283,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            107 => 
            array (
                'id_pack_experience' => 184,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 288,
                'id_experience' => 284,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            108 => 
            array (
                'id_pack_experience' => 185,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 289,
                'id_experience' => 285,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            109 => 
            array (
                'id_pack_experience' => 186,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 290,
                'id_experience' => 286,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            110 => 
            array (
                'id_pack_experience' => 187,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 291,
                'id_experience' => 287,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            111 => 
            array (
                'id_pack_experience' => 188,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 292,
                'id_experience' => 288,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            112 => 
            array (
                'id_pack_experience' => 189,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 293,
                'id_experience' => 289,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            113 => 
            array (
                'id_pack_experience' => 190,
                'nb_titres' => 4,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 294,
                'id_experience' => 290,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            114 => 
            array (
                'id_pack_experience' => 191,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 295,
                'id_experience' => 291,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            115 => 
            array (
                'id_pack_experience' => 192,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 296,
                'id_experience' => 292,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            116 => 
            array (
                'id_pack_experience' => 193,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 297,
                'id_experience' => 293,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            117 => 
            array (
                'id_pack_experience' => 194,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 298,
                'id_experience' => 294,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            118 => 
            array (
                'id_pack_experience' => 195,
                'nb_titres' => 1,
                'nb_participants' => 14,
                'id_pack' => 13,
                'num_facture' => 299,
                'id_experience' => 295,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            119 => 
            array (
                'id_pack_experience' => 196,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 300,
                'id_experience' => 296,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            120 => 
            array (
                'id_pack_experience' => 197,
                'nb_titres' => 1,
                'nb_participants' => 8,
                'id_pack' => 6,
                'num_facture' => 301,
                'id_experience' => 297,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            121 => 
            array (
                'id_pack_experience' => 198,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 302,
                'id_experience' => 298,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            122 => 
            array (
                'id_pack_experience' => 199,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 8,
                'num_facture' => 303,
                'id_experience' => 299,
                'id_liste_prix' => 21,
                'id_historique_remise' => NULL,
            ),
            123 => 
            array (
                'id_pack_experience' => 200,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 304,
                'id_experience' => 300,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            124 => 
            array (
                'id_pack_experience' => 201,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 305,
                'id_experience' => 301,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            125 => 
            array (
                'id_pack_experience' => 202,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 306,
                'id_experience' => 302,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            126 => 
            array (
                'id_pack_experience' => 203,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 307,
                'id_experience' => 303,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            127 => 
            array (
                'id_pack_experience' => 204,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 7,
                'num_facture' => 308,
                'id_experience' => 304,
                'id_liste_prix' => 22,
                'id_historique_remise' => NULL,
            ),
            128 => 
            array (
                'id_pack_experience' => 205,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 309,
                'id_experience' => 305,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            129 => 
            array (
                'id_pack_experience' => 206,
                'nb_titres' => 3,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 310,
                'id_experience' => 306,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            130 => 
            array (
                'id_pack_experience' => 207,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 311,
                'id_experience' => 307,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            131 => 
            array (
                'id_pack_experience' => 208,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 312,
                'id_experience' => 308,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            132 => 
            array (
                'id_pack_experience' => 209,
                'nb_titres' => 2,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 313,
                'id_experience' => 309,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            133 => 
            array (
                'id_pack_experience' => 210,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 314,
                'id_experience' => 310,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            134 => 
            array (
                'id_pack_experience' => 211,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 315,
                'id_experience' => 311,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            135 => 
            array (
                'id_pack_experience' => 212,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 316,
                'id_experience' => 312,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            136 => 
            array (
                'id_pack_experience' => 213,
                'nb_titres' => 1,
                'nb_participants' => 2,
                'id_pack' => 13,
                'num_facture' => 317,
                'id_experience' => 313,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            137 => 
            array (
                'id_pack_experience' => 214,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 318,
                'id_experience' => 314,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            138 => 
            array (
                'id_pack_experience' => 215,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 319,
                'id_experience' => 315,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            139 => 
            array (
                'id_pack_experience' => 216,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 321,
                'id_experience' => 316,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            140 => 
            array (
                'id_pack_experience' => 217,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 323,
                'id_experience' => 317,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            141 => 
            array (
                'id_pack_experience' => 218,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 13,
                'num_facture' => 324,
                'id_experience' => 318,
                'id_liste_prix' => 5,
                'id_historique_remise' => NULL,
            ),
            142 => 
            array (
                'id_pack_experience' => 219,
                'nb_titres' => 1,
                'nb_participants' => 6,
                'id_pack' => 6,
                'num_facture' => 325,
                'id_experience' => 319,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            143 => 
            array (
                'id_pack_experience' => 220,
                'nb_titres' => 1,
                'nb_participants' => 9,
                'id_pack' => 6,
                'num_facture' => 327,
                'id_experience' => 320,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            144 => 
            array (
                'id_pack_experience' => 221,
                'nb_titres' => 1,
                'nb_participants' => 14,
                'id_pack' => 3,
                'num_facture' => 328,
                'id_experience' => 321,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            145 => 
            array (
                'id_pack_experience' => 222,
                'nb_titres' => 1,
                'nb_participants' => 10,
                'id_pack' => 6,
                'num_facture' => 329,
                'id_experience' => 322,
                'id_liste_prix' => 9,
                'id_historique_remise' => NULL,
            ),
            146 => 
            array (
                'id_pack_experience' => 223,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 7,
                'num_facture' => 345,
                'id_experience' => 323,
                'id_liste_prix' => 22,
                'id_historique_remise' => NULL,
            ),
            147 => 
            array (
                'id_pack_experience' => 224,
                'nb_titres' => 1,
                'nb_participants' => 5,
                'id_pack' => 2,
                'num_facture' => 346,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            148 => 
            array (
                'id_pack_experience' => 225,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 355,
                'id_experience' => 324,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            149 => 
            array (
                'id_pack_experience' => 226,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 357,
                'id_experience' => 325,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            150 => 
            array (
                'id_pack_experience' => 227,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 358,
                'id_experience' => 326,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            151 => 
            array (
                'id_pack_experience' => 228,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 359,
                'id_experience' => 327,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            152 => 
            array (
                'id_pack_experience' => 229,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 360,
                'id_experience' => 328,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            153 => 
            array (
                'id_pack_experience' => 230,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 361,
                'id_experience' => 329,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            154 => 
            array (
                'id_pack_experience' => 231,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 362,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            155 => 
            array (
                'id_pack_experience' => 232,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 15,
                'num_facture' => 363,
                'id_experience' => 330,
                'id_liste_prix' => 49,
                'id_historique_remise' => NULL,
            ),
            156 => 
            array (
                'id_pack_experience' => 233,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 364,
                'id_experience' => 331,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            157 => 
            array (
                'id_pack_experience' => 234,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 365,
                'id_experience' => 332,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            158 => 
            array (
                'id_pack_experience' => 235,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 366,
                'id_experience' => 333,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            159 => 
            array (
                'id_pack_experience' => 236,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 16,
                'num_facture' => 367,
                'id_experience' => 334,
                'id_liste_prix' => 50,
                'id_historique_remise' => NULL,
            ),
            160 => 
            array (
                'id_pack_experience' => 237,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 18,
                'num_facture' => 368,
                'id_experience' => 335,
                'id_liste_prix' => 52,
                'id_historique_remise' => NULL,
            ),
            161 => 
            array (
                'id_pack_experience' => 238,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 369,
                'id_experience' => 336,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            162 => 
            array (
                'id_pack_experience' => 239,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 369,
                'id_experience' => 337,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            163 => 
            array (
                'id_pack_experience' => 240,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 369,
                'id_experience' => 338,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            164 => 
            array (
                'id_pack_experience' => 241,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 370,
                'id_experience' => 339,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            165 => 
            array (
                'id_pack_experience' => 242,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 370,
                'id_experience' => 340,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            166 => 
            array (
                'id_pack_experience' => 243,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 370,
                'id_experience' => 341,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            167 => 
            array (
                'id_pack_experience' => 244,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 371,
                'id_experience' => 342,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            168 => 
            array (
                'id_pack_experience' => 245,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 371,
                'id_experience' => 343,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            169 => 
            array (
                'id_pack_experience' => 246,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 371,
                'id_experience' => 344,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            170 => 
            array (
                'id_pack_experience' => 247,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 372,
                'id_experience' => 345,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            171 => 
            array (
                'id_pack_experience' => 248,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 372,
                'id_experience' => 346,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            172 => 
            array (
                'id_pack_experience' => 249,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 372,
                'id_experience' => 347,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            173 => 
            array (
                'id_pack_experience' => 250,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 373,
                'id_experience' => 348,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            174 => 
            array (
                'id_pack_experience' => 251,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 373,
                'id_experience' => 349,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            175 => 
            array (
                'id_pack_experience' => 252,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 373,
                'id_experience' => 350,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            176 => 
            array (
                'id_pack_experience' => 253,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 374,
                'id_experience' => 351,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            177 => 
            array (
                'id_pack_experience' => 254,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 374,
                'id_experience' => 352,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            178 => 
            array (
                'id_pack_experience' => 255,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 374,
                'id_experience' => 353,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            179 => 
            array (
                'id_pack_experience' => 256,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 375,
                'id_experience' => 354,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            180 => 
            array (
                'id_pack_experience' => 257,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 375,
                'id_experience' => 355,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            181 => 
            array (
                'id_pack_experience' => 258,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 375,
                'id_experience' => 356,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            182 => 
            array (
                'id_pack_experience' => 259,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 376,
                'id_experience' => 357,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            183 => 
            array (
                'id_pack_experience' => 260,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 376,
                'id_experience' => 358,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            184 => 
            array (
                'id_pack_experience' => 261,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 376,
                'id_experience' => 359,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            185 => 
            array (
                'id_pack_experience' => 262,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 377,
                'id_experience' => 360,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            186 => 
            array (
                'id_pack_experience' => 263,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 377,
                'id_experience' => 361,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            187 => 
            array (
                'id_pack_experience' => 264,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 377,
                'id_experience' => 362,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            188 => 
            array (
                'id_pack_experience' => 265,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 378,
                'id_experience' => 363,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            189 => 
            array (
                'id_pack_experience' => 266,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 378,
                'id_experience' => 364,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            190 => 
            array (
                'id_pack_experience' => 267,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 378,
                'id_experience' => 365,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            191 => 
            array (
                'id_pack_experience' => 268,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 379,
                'id_experience' => 366,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            192 => 
            array (
                'id_pack_experience' => 269,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 379,
                'id_experience' => 367,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            193 => 
            array (
                'id_pack_experience' => 270,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 379,
                'id_experience' => 368,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            194 => 
            array (
                'id_pack_experience' => 271,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 380,
                'id_experience' => 369,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            195 => 
            array (
                'id_pack_experience' => 272,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 380,
                'id_experience' => 370,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            196 => 
            array (
                'id_pack_experience' => 273,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 380,
                'id_experience' => 371,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            197 => 
            array (
                'id_pack_experience' => 274,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 381,
                'id_experience' => 372,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            198 => 
            array (
                'id_pack_experience' => 275,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 381,
                'id_experience' => 373,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            199 => 
            array (
                'id_pack_experience' => 276,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 381,
                'id_experience' => 374,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            200 => 
            array (
                'id_pack_experience' => 277,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 382,
                'id_experience' => 375,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            201 => 
            array (
                'id_pack_experience' => 278,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 382,
                'id_experience' => 376,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            202 => 
            array (
                'id_pack_experience' => 279,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 382,
                'id_experience' => 377,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            203 => 
            array (
                'id_pack_experience' => 280,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 383,
                'id_experience' => 378,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            204 => 
            array (
                'id_pack_experience' => 281,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 383,
                'id_experience' => 379,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            205 => 
            array (
                'id_pack_experience' => 282,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 383,
                'id_experience' => 380,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            206 => 
            array (
                'id_pack_experience' => 283,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 391,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            207 => 
            array (
                'id_pack_experience' => 284,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 393,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            208 => 
            array (
                'id_pack_experience' => 285,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 393,
                'id_experience' => NULL,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            209 => 
            array (
                'id_pack_experience' => 286,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 394,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            210 => 
            array (
                'id_pack_experience' => 287,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 394,
                'id_experience' => NULL,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            211 => 
            array (
                'id_pack_experience' => 288,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 395,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            212 => 
            array (
                'id_pack_experience' => 289,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 395,
                'id_experience' => NULL,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            213 => 
            array (
                'id_pack_experience' => 290,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 396,
                'id_experience' => 381,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            214 => 
            array (
                'id_pack_experience' => 291,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 3,
                'num_facture' => 396,
                'id_experience' => 382,
                'id_liste_prix' => 12,
                'id_historique_remise' => NULL,
            ),
            215 => 
            array (
                'id_pack_experience' => 292,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 397,
                'id_experience' => 383,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            216 => 
            array (
                'id_pack_experience' => 293,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 398,
                'id_experience' => 385,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            217 => 
            array (
                'id_pack_experience' => 294,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 399,
                'id_experience' => 387,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            218 => 
            array (
                'id_pack_experience' => 295,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 400,
                'id_experience' => 389,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            219 => 
            array (
                'id_pack_experience' => 296,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 401,
                'id_experience' => 390,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            220 => 
            array (
                'id_pack_experience' => 297,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 402,
                'id_experience' => 391,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            221 => 
            array (
                'id_pack_experience' => 298,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 403,
                'id_experience' => 393,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            222 => 
            array (
                'id_pack_experience' => 299,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 404,
                'id_experience' => 394,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            223 => 
            array (
                'id_pack_experience' => 300,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 405,
                'id_experience' => 395,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            224 => 
            array (
                'id_pack_experience' => 301,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 406,
                'id_experience' => 396,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            225 => 
            array (
                'id_pack_experience' => 302,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 407,
                'id_experience' => 397,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            226 => 
            array (
                'id_pack_experience' => 303,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 408,
                'id_experience' => 399,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            227 => 
            array (
                'id_pack_experience' => 304,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 409,
                'id_experience' => 400,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            228 => 
            array (
                'id_pack_experience' => 305,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 410,
                'id_experience' => 401,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            229 => 
            array (
                'id_pack_experience' => 306,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 411,
                'id_experience' => 402,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            230 => 
            array (
                'id_pack_experience' => 307,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 412,
                'id_experience' => 403,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            231 => 
            array (
                'id_pack_experience' => 308,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 413,
                'id_experience' => 405,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            232 => 
            array (
                'id_pack_experience' => 309,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 414,
                'id_experience' => 407,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            233 => 
            array (
                'id_pack_experience' => 310,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 420,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            234 => 
            array (
                'id_pack_experience' => 311,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 421,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            235 => 
            array (
                'id_pack_experience' => 312,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 422,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            236 => 
            array (
                'id_pack_experience' => 313,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 423,
                'id_experience' => NULL,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            237 => 
            array (
                'id_pack_experience' => 314,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 424,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            238 => 
            array (
                'id_pack_experience' => 315,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 425,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            239 => 
            array (
                'id_pack_experience' => 316,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 427,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            240 => 
            array (
                'id_pack_experience' => 317,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 428,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            241 => 
            array (
                'id_pack_experience' => 318,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 1,
                'num_facture' => 430,
                'id_experience' => NULL,
                'id_liste_prix' => 7,
                'id_historique_remise' => NULL,
            ),
            242 => 
            array (
                'id_pack_experience' => 319,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 437,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
            243 => 
            array (
                'id_pack_experience' => 320,
                'nb_titres' => 1,
                'nb_participants' => 1,
                'id_pack' => 2,
                'num_facture' => 438,
                'id_experience' => NULL,
                'id_liste_prix' => 26,
                'id_historique_remise' => NULL,
            ),
        ));
        
        
    }
}