<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProduitsServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('produits_services')->delete();
        
        \DB::table('produits_services')->insert(array (
            0 => 
            array (
                'id_produit' => 1,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'produit',
                'date_creation' => '2022-06-02 15:23:21',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => '45 tours - Vinyle',
                'prix' => '70.00',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            1 => 
            array (
                'id_produit' => 2,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-08-18 14:44:30',
                'date_update' => NULL,
                'statut' => 'archivé',
                'nom_produit' => 'Coatching',
                'prix' => '35',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            2 => 
            array (
                'id_produit' => 3,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'produit',
                'date_creation' => '2022-12-21 10:48:31',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Bon cadeau',
                'prix' => '0.00',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            3 => 
            array (
                'id_produit' => 4,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-06-02 15:22:23',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Titre',
                'prix' => '85.00',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            4 => 
            array (
                'id_produit' => 5,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2021-06-05 00:00:00',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Personne Supp Expérience EVJF',
                'prix' => '40.00',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            5 => 
            array (
                'id_produit' => 6,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-05-21 10:57:19',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Enregistrement Instrument Supplémentaire',
                'prix' => '40.00',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            6 => 
            array (
                'id_produit' => 10,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-05-21 10:54:19',
                'date_update' => NULL,
                'statut' => 'actif',
            'nom_produit' => 'Personnes supplémentaires ( + de 10)',
                'prix' => '35',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            7 => 
            array (
                'id_produit' => 11,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-05-21 10:59:19',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Coaching Pré enregistrement 1h',
                'prix' => '35',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            8 => 
            array (
                'id_produit' => 12,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-02-01 00:00:00',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Séance studio Préparation Vocal Nouvel Arrangement',
                'prix' => '85',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            9 => 
            array (
                'id_produit' => 13,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2022-01-13 00:00:00',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Vidéo Clip',
                'prix' => '300',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            10 => 
            array (
                'id_produit' => 14,
                'abstract' => NULL,
                'description' => NULL,
                'categorie' => 'experience',
                'date_creation' => '2021-01-27 00:00:00',
                'date_update' => NULL,
                'statut' => 'actif',
                'nom_produit' => 'Personne supplémentaire',
                'prix' => '40',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            11 => 
            array (
                'id_produit' => 16,
                'abstract' => 'Sous titrage vidéo',
                'description' => 'Réalisation des sous-titres d\'une vidéo — sans suivi Karaoké',
                'categorie' => 'produit',
                'date_creation' => '2023-06-29 10:59:24',
                'date_update' => '2023-06-29 10:59:24',
                'statut' => 'actif',
                'nom_produit' => 'Sous-titrage Vidéo Clip',
                'prix' => '60',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            12 => 
            array (
                'id_produit' => 17,
                'abstract' => 'Sous-Titrage',
                'description' => 'Sous-Titrage Expérience Orange',
                'categorie' => 'produit',
                'date_creation' => '2023-06-29 16:47:47',
                'date_update' => '2023-06-29 16:47:47',
                'statut' => 'actif',
                'nom_produit' => 'Sous Titrage',
                'prix' => '120',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            13 => 
            array (
                'id_produit' => 18,
                'abstract' => 'Expérience 1€',
                'description' => 'Expérience 1€',
                'categorie' => 'produit',
                'date_creation' => '2022-12-26 18:35:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Expérience 1€',
                'prix' => '1',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            14 => 
            array (
                'id_produit' => 19,
                'abstract' => 'Prise de voix',
                'description' => 'Prise de voix',
                'categorie' => 'experience',
                'date_creation' => '2023-05-25 19:02:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Prise de voix',
                'prix' => '60',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            15 => 
            array (
                'id_produit' => 20,
                'abstract' => 'Payement facture test',
                'description' => 'Payement facture test',
                'categorie' => 'produit',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Payement facture test',
                'prix' => '5',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            16 => 
            array (
                'id_produit' => 21,
                'abstract' => 'Versement rembousement LALACHANTE TEST',
                'description' => 'Versement rembousement LALACHANTE TEST',
                'categorie' => 'produit',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Versement rembousement LALACHANTE TEST',
                'prix' => '5',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            17 => 
            array (
                'id_produit' => 22,
                'abstract' => 'Vidéo Tournage et montage Intermédiaire',
                'description' => 'Vidéo Tournage et montage Intermédiaire',
                'categorie' => 'produit',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Vidéo Tournage et montage Intermédiaire',
                'prix' => '150',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            18 => 
            array (
                'id_produit' => 23,
            'abstract' => 'Clip expérience ( Tournage Montage)',
            'description' => 'Clip expérience ( Tournage Montage)',
                'categorie' => 'produit',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
            'nom_produit' => 'Clip expérience ( Tournage Montage)',
                'prix' => '200',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            19 => 
            array (
                'id_produit' => 24,
                'abstract' => 'Enregistrement Guitare acoustique',
                'description' => 'Enregistrement Guitare acoustique',
                'categorie' => 'produit',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Enregistrement Guitare acoustique',
                'prix' => '45',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            20 => 
            array (
                'id_produit' => 25,
                'abstract' => 'Disque vinyle Pochette photo pressage Mastering
',
                'description' => 'Disque vinyle Pochette photo pressage Mastering',
                'categorie' => 'produit',
                'date_creation' => '2021-08-29 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Disque vinyle Pochette photo pressage Mastering',
                'prix' => '75',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            21 => 
            array (
                'id_produit' => 26,
                'abstract' => 'Composition Instru',
                'description' => 'Composition Instru',
                'categorie' => 'produit',
                'date_creation' => '2020-07-21 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Composition Instru',
                'prix' => '220',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            22 => 
            array (
                'id_produit' => 27,
                'abstract' => 'Disque vinyle / Préssage 1 exemplaire',
                'description' => 'Disque vinyle / Préssage 1 exemplaire',
                'categorie' => '',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Disque vinyle / Préssage 1 exemplaire',
                'prix' => '45',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            23 => 
            array (
                'id_produit' => 28,
                'abstract' => 'Création graphique & photo',
                'description' => 'Création graphique & photo',
                'categorie' => '',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Création graphique & photo',
                'prix' => '20',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            24 => 
            array (
                'id_produit' => 29,
                'abstract' => 'Frais d\'envoi postale',
                'description' => 'Frais d\'envoi postale',
                'categorie' => '',
                'date_creation' => '2020-05-08 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Frais d\'envoi postale',
                'prix' => '6,45',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            25 => 
            array (
                'id_produit' => 30,
                'abstract' => 'Réenregistrement',
                'description' => 'Réenregistrement',
                'categorie' => '',
                'date_creation' => '2023-05-25 19:45:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'actif',
                'nom_produit' => 'Réenregistrement',
                'prix' => '60',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            26 => 
            array (
                'id_produit' => 31,
                'abstract' => 'Accompagnement personnalisé projet d\'artiste compostions',
                'description' => 'Accompagnement personnalisé projet d\'artiste compostions',
                'categorie' => '',
                'date_creation' => '2022-01-29 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Accompagnement personnalisé projet d\'artiste compo',
                'prix' => '40',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            27 => 
            array (
                'id_produit' => 32,
                'abstract' => 'Ré- Arrangement export nouvel Bande Son',
                'description' => 'Ré- Arrangement export nouvel Bande Son',
                'categorie' => '',
                'date_creation' => '2022-02-01 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Ré- Arrangement export nouvel Bande Son',
                'prix' => '85',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
            28 => 
            array (
                'id_produit' => 33,
                'abstract' => 'Séance studio Préparation Vocal sur Nouvel Arrangement',
                'description' => 'Séance studio Préparation Vocal sur Nouvel Arrangement',
                'categorie' => '',
                'date_creation' => '2022-02-01 00:00:00',
                'date_update' => '0000-00-00 00:00:00',
                'statut' => 'archivé',
                'nom_produit' => 'Séance studio Préparation Vocal sur Nouvel Arrange',
                'prix' => '85',
                'stock' => NULL,
                'id_stripe_produit' => NULL,
                'url_stripe_produit' => NULL,
            ),
        ));
        
        
    }
}